### ISSUE TITLE
 individuals/CRUD/qa

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#152]
### Functionality Checklist 
- [x] 1. Back-end tests written for Add a new Event_Person (e.g., keynote speaker)    
- [x] 2. End-to-end tests written to Add a new Event_Person (e.g., keynote speaker)    
   - [x] Testing for allowing the Person to be chosen in the following ways:
       - [x] An existing Person, using live search.
       - [x] Ensure that a Person is not double-booked.
- [x] 3. Back-end tests written for Update/Delete functionality for Event_Person; provide the same capabilities as when creating a new Event_Person. 
- [x] 4. End-to-end tests written for Update/Delete functionality for Event_Person; provide the same capabilities as when creating a new Event_Person.

**Comment by Noahffiliation** [comment]
No functionality to create a new person on the fly
