### ISSUE TITLE
 individuals/CRUD/ui

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#153]
## Individuals - CRUD - UI
branch to merge changes => _app-events-individuals_
### Functionality Checklist 
- [x] 1. UI is able to add a new Event_Person (e.g., keynote speaker)    
   - [x] UI is able to allow the Person to be chosen in the following ways:
       * An existing Person, using live search.
       * Ensure that an Person is not double-booked.
- [x] 2. UI is able to Update/Delete an Event_Person; provide the same capabilities as when creating a new Event_Person. 
- [x] 3. API integration complete
- [x] 4. End-to-end test cases started (collaborating with QA team)

**Comment by JoeyFerg** [comment]
Done with everything except adding a new person.
