### ISSUE TITLE
ui-bug-fixes

### ISSUE THREAD

**Issue by bshelor** [corpus-christi/corpus-christi#219]
- [x] Log out button does not appear clickable
- [x] When entering a birthday for a person, you should not be able to set it in the future
- [x] The phone # field should be limited. Currently, there is no limit to numbers entered
- [x] The phone # field should also only accept numbers - double check this - this will be taken care of in the customization story cards
- [x] The name field should only allow letters
- [x] Incorrect login credentials should display an error
- [x] An expired session token should automatically log a user out
- [x] When the roles tab in persons page is made half-screen, the column for username is covered up by actions. This should not happen
- [x] The save button in roles tab for edit user is just a blue button, and does not say the word save in either language choice
- [x] The field for assigning roles says $tRoles which means there is a translation problem, maybe UI related? 
- [x] The password reset/entry error should probably give a reason why the password entry is incorrect, instead of just saying 'error'
- [x] Adding roles to a person in the roles tab assigns the role to every person. The same applies for deleting a role. This is bad
- [x] Should be able to search for a person by their username in the roles tab
- [x] The ascending/descending/neutral sort for usernames in roles tab should do stuff
- [x] The dropdown in roles should have a neutral option to be able to see all accounts (like default)
- [x] When making an account for someone, their person can be archived, but their account appears active. Maybe shouldn't be able to make an account for an inactive person. Will no longer be needed because of db changes
- [x] Text fields should allow certain characters that occur in names, such as apostrophe '

**Comment by david-fletcher** [comment]
@andrewdorn1 , we cannot validate phone numbers. It is computationally too difficult to validate phone numbers across different locales; a conversation with Dr. Nurkkala informed me that even in industry, phone numbers are often left unvalidated because it is too difficult

**Comment by david-fletcher** [comment]
@bshelor , the token redirection is mostly working. Nurk said move onto something else. I may work on it over the weekend though.
