### ISSUE TITLE
Diploma page needs indication of hidden content

### ISSUE THREAD

**Issue by nurkkala** [corpus-christi/corpus-christi#242]
On the diploma page, there is no visual indication of additional content available about each diploma. Needs some kind of icon. Also, when the hidden content opens, the rules on the page seem to suggest that the details go with the _next_ diploma rather than the one just clicked.

**Comment by knkiers** [comment]
clicking on a row in the diplomas table now takes the user to a diploma detail page, which is more consistent with the behaviour in the rest of the app
