### ISSUE TITLE
images/CRUD/api

### ISSUE THREAD

**Issue by MattHapner** [corpus-christi/corpus-christi#247]
### Functionality Checklist
- [x] 1. Allow a new image to be uploaded to the file system (at /api/data/images).
- [x] 1.1 Optionally allow a description to be added to the image.
- [x] 2. Allow an existing image to be downloaded.
- [x] 3. Allow an existing image to have it's description updated.
- [x] 4. Allow the deletion of existing images.
- [x] 5. Back-end test cases started (helping work with QA team)
- [x] 6. Integrate and hand-off this API with the UI team

**Comment by mattlou077** [comment]
Testing using pytest in api/src/images/test_images.py needs to be completed.
