### ISSUE TITLE
Auto-fill field for managers when duplicating a home group

### ISSUE THREAD

**Issue by sethlugibihl** [corpus-christi/corpus-christi#254]
Auto-fill the entity search field for managers when duplicating ("add another") a homegroup

## UI
 - [ ] Auto-fill manager search field while duplicating.
 - [ ] Manually test to make sure this works.

**Comment by mattddean** [comment]
Attempted, but did not succeed: https://github.com/corpus-christi/corpus-christi/commit/3e06ea42575cd8e729296f96adc9dd95d88be77b
