### ISSUE TITLE
User Translation UI

### ISSUE THREAD

**Issue by connorwagner** [corpus-christi/corpus-christi#263]
- [x] Allow a user to provide a new translation
    - [x] Should be searchable/filterable
        - [x] Translator can verify accuracy
    - [x] Show selected existing translations for reference
- [x] Allow a user to update an existing translation
- [x] Command line utility to add a new translation

**Comment by josephvanderharst** [comment]
The ```flask i18n``` CLI-suite of commands already includes 'add,' 'delete,' 'dump,' 'edit,' 'load,' and 'update'. See [api/src/cli/i18n.py](https://github.com/corpus-christi/corpus-christi/blob/development/api/src/cli/i18n.py) for details.
The 'add' and 'delete' and 'update' commands serve as a command-line utility to add translations and keys.
