### ISSUE TITLE
Confirm Repeat Password Functionality/Testing on Account Creation

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#314]
The repeat password functionality broke during the final presentation in Ecuador.  The system lets a user make an account before the confirmed their password.  

- [ ] Fix confirm password/ensure this does not break
- [ ] Create a test to confirm the system wont let a user create an account

**Comment by MattHapner** [comment]
Jason - I am not able to replicate this issue? It seems to be requiring a password confirmation when a user is registering.
