### ISSUE TITLE
Ensure dates cannot be added to a Person record before they are born

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#318]
- [x] UI is validated to ensure a Person record cannot be added before they are born
- [ ] A QA test is written to ensure this edge case

**Comment by bromlu** [comment]
@jasonlargo what is a person record?

**Comment by jasonlargo** [comment]
@bromlu An entry in the "person" table.

**Comment by bromlu** [comment]
The feature is done, but I don't think the tests are. Currently we are only passing 51 out of 235 though... Will probably talk to @nurkkala about taking the time to fix all the tests or abandoning cypress for now.

**Comment by bromlu** [comment]
We are abandoning cypress tests for now.
