### ISSUE TITLE
Test home group manager

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#319]
The Home Group manager page was broken during our presentation in Cuenca.

- [ ] experimented with the group manager page and try and break it
- [ ] Report any issues via comments in this issue.

**Comment by bromlu** [comment]
@jasonlargo Need clarification on what the heck a manger is... things aren't set up right here and it will take some time to fix, so I want to make sure that I am fixing it the right way before I move forward. We will probably have to talk in person about this or maybe with @nurkkala.

**Comment by PROgram52bc** [comment]
replaced by the new model's user interface #557
