### ISSUE TITLE
Ensure that if a user tries to sign up for a course that is archived, they cannot sign up for it.

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#324]
If someone tries to sign up for a course that is archived can they sign up for the course again?
- [x] Ensure that if a course is archived, they cannot sign up for it again.

**Comment by stephen-boxerman** [comment]
Was taken care of by whomever worked on the Upcoming Courses page.  Since this is the only place registration is currently happening, and only active courses are shown,  this issue is dealt with.
