### ISSUE TITLE
Filter groups by meeting times and dates

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#334]
- Build out functionality for a user to filter groups by their meeting times and dates 

Note: Look at the current website for how this is implemented.

This will allow users of the system to easily find a home group that could work with their schedule.

**Comment by ChrisMaxel** [comment]
I could not find "the current website" and filtering groups by meeting times and dates.
[This](https://www.arcoministries.org/about-us) is the arco church website that I found, but when clicking around, I didn't find any filtering options.

**Comment by quiteqiang** [comment]
The current features solve this problem
