### ISSUE TITLE
The Image Project

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#335]
Build out functionality for attaching and displaying images for:

- [x] events
- [x] people
- [ ] groups
- [ ] places
- [x] courses
- [ ] other entities that might want photos as they come up

Store the images in the database and retrieve them with proper api calls to be displayed appropriately for the various entities.  Place any necessary restrictions on users (image size, dimensions), and display the images in a aesthetically pleasing visually consistent manner throughout the system.

Note: Edric, Joey F, and Ryan H have worked on this for events.  Follow their conventions and ask them for help on this.  

This will involve some extensive work on both the DB, API, and UI

**Comment by david-fletcher** [comment]
@jasonlargo , We have created a component that handles choosing an image that can nearly plug-n-play with other forms across the site. We'll begin generalizing our solution once Josh's PR gets merge into development since he's doing a lot of refactoring and we'd like to avoid merge conflicts
