### ISSUE TITLE
Wiki/doc clean up

### ISSUE THREAD

**Issue by Noahffiliation** [corpus-christi/corpus-christi#345]
The wiki is currently incomplete, and some of the information is already written up in the `doc` directory. Wondering if it would be beneficial to either import wiki information into `doc`, complete the wiki, or import `doc` into the wiki?

@bromlu Any thoughts on this?

**Comment by nurkkala** [comment]
The Wiki never really got off the ground; ignore it for now.  All the updated documentation is in the `docs` directory.
