### ISSUE TITLE
Fix Group's member archive pop-up

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#376]
Upon clicking the archive button for a member in Groups (aka. Home church), the pop-up shows:
![image](https://user-images.githubusercontent.com/29484426/71987284-e9f63300-31fb-11ea-9ac2-7959f3efab41.png)
1. We don't want to archive the group, just the single person in the group.  The wording needs to be fixed to something like, `Are you sure you would like to archive this person?`.
     - [x] Fix wording of group member's pop-up box.

2. We need to make sure that this button works appropriately and we can archive the person.
     - [x] Manually test the backend to ensure that the user shows an archived status from the group members' table.

3. We need to test this to make sure that someone didn't copy and paste this code.  If this action archives the group, this is wrong.  We only want the archive button to archive the single person.
     - [x] Manually test to make sure that the archive button only archives the person and not the group.

4. Make sure that the translation works properly because we are changing the wording.
    - [x] Switch from English to Spanish and try your best to confirm it actually translates to something meaningful.

**Comment by nurkkala** [comment]
Although this is in "submitted pull requests," I don't see a pull request for it.
