### ISSUE TITLE
Do not allow for groups to be deleted

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#379]
This may be a lot to follow, so if you have questions, please contact Chris Maxel.

I noticed that groups were being deleted and removed from the page (and probably the DB).

Steps to delete a page:
    1. Create (or select) a group that is easy to remember.  (Note. Pay attention to the number of groups at the bottom right-hand corner of the table)
    2. Add/have members to this group (I added 2).
    3. Archive the group.
    4. Go to the group members page and Archive a Person (Note. If the user is already archived, the unarchive button also will delete the group).

Upon doing this, the group is deleted.

- [ ] Confirm that upon completing this process things are not being deleted anymore
- [ ] Test functionality for arching groups and members.  Comment on this issue if there are still issues with archiving/un-archiving in members and groups.

**Comment by wirrickelliot** [comment]
This appears to happen if you just go to the details page of an archived group.
