### ISSUE TITLE
Admin: Move group members from one group to another

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#381]
As an admin, be able to move a Group Member from one Group to another existing Group.

In the list of members for a group, add a button to actions that is only visible for admins (and not for general users) to move a group member from one group to another.

- [ ] Add one more button to actions that has an icon that communicates moving a person (make sure the icon looks different than the archive icon)(note. this may require API work).
- [ ] After the additional button is clicked, have a confirmation pop up appear with `cancel` and `continue` options.  Also, include a drop-down menu where the admin can select the desired group to place the member in.
- [ ] Update the Database removing the person from the selected group and adds them to the other desired group
- [ ] Manually test to confirm that the user is removed from the current group and added to the new desired group.

**Comment by mattddean** [comment]
I doesn't seem like non-admin roles exist, so we likely won't be able to create the functionality where only admins can do this.

**Comment by nurkkala** [comment]
When you say they don't exist, do you mean there aren't any currently in the test data or the roles haven't been loaded, or something more sinister?
