### ISSUE TITLE
Create Meetings tab for each group

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#383]
When clicking on a group on the group's page, you are taken to the details page.  Next to details is members, add a tab on the top for meetings that once clicked takes you to the meetings page.

![image](https://user-images.githubusercontent.com/29484426/72003405-4b77cb00-3217-11ea-97b5-8470b109a180.png)

In the meetings tab (for now), have a simple page that has the group name at the top.

- [x] Create a simple Meetings page (changes the link at the top similarly to details and members)
- [x] Add a tab to the details page for members
- [x] Make sure that you can click between the three of them seamlessly.
- [x] Remove the buttons from the details page because they are no longer needed.

**Comment by nurkkala** [comment]
Nice story card -- pictures!
