### ISSUE TITLE
Groups - Give more details error messages when attempting to save a group with invalid fields

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#395]
It seems to be that when creating a group, a Name, Description, and Manager are all required fields.  When attempting to save or add another group with an invalid field (blank, etc.) the only error message that is displayed is "Error while adding group."
![image](https://user-images.githubusercontent.com/29484426/72169376-febdfc80-339c-11ea-8368-a577d876a5a5.png)

We should add in more descriptive error messages in these scenarios to help the user create a group.
To keep things visually consistent, we should try to model how courses looks:
![image](https://user-images.githubusercontent.com/29484426/72169512-3f1d7a80-339d-11ea-98cc-beea652da94b.png)

- [x] Figure out what validation is done here to understand the constraints.
- [x] When attempting to save things with invalid fields, highlight the invalid filed in red (make it jiggle a little, look at courses and try to save with empty invalid fields)
- [x] When attempting to save invalid fields, display a description in red giving the reason why the field is invalid.

**Comment by jordaniwoodtaylor** [comment]
Bug found: Doesn't give error messages for required field "Manager"
