### ISSUE TITLE
Groups - refactor database to remove all back_populates in favor of backref

### ISSUE THREAD

**Issue by mattddean** [corpus-christi/corpus-christi#399]

**Comment by mattddean** [comment]
When dealing with relationships, boil.py produces exlusively backref and never back_populates. This refactor will involve updating boilerplate/*.yaml files and then using the output based on those to update *.models.py files.

Acceptance Criteria:
- no back_populates in any *.models.py files.

**Comment by nurkkala** [comment]
Per discussion with @mattddean , this will simplify the code without sacrificing readability very much in that the FK information is still in the "other" table. More info in the [SQL Alchemy docs](https://docs.sqlalchemy.org/en/13/orm/backref.html#relationships-backref).

**Comment by quiteqiang** [comment]
We will keep using **back_populates** since it is easier to understand the code without going having to go look at the other side of a relationship

**Comment by PROgram52bc** [comment]
All existing `back_ref`s should be updated to `back_populates`, and the reverse side should have a corresponding `back_populates` as well
