### ISSUE TITLE
Groups - Create documentation and set-up processes for sending email as a manager

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#426]
Create documentation for group managers to help them mass send emails to group members.

- [x] Explain Gmail setup (eg.. 2-step varification set-up)
~~Specify if it needs to be a gmail account~~
~~Include images~~
[sdfasdf](url)

**Comment by wirrickelliot** [comment]
The group managers themselves aren't going to have to configure sending emails--it would be done by whomever sets up the flask server.
