### ISSUE TITLE
Groups - add group button - Group leader role

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#441]
When a manager is assigned to a group, the person (that is the manager) should be assigned the `group leader` role.

- [ ] Before starting this story, make sure that every user has an account (as of today (1/17/2020) roles are not working properly).
- [ ] When a person is assigned to be a manager of a group and the change/creation is saved, they should also be assigned the `group leader` role in the database.
- [ ] Manually test that this works - after creating a group with a manager, go to the people's page and roles tab to see if our new manager is assigned the role `group leader`.
- [ ] Manually test that this works - after editing a group and changing the manager, go to the people's page and roles tab to see if our new manager is assigned the role `group leader` and the old leader still has the role `group leader`.

Note that if a group leader is changed, the old leader should still have the `group leader` tag in roles.

**Comment by PROgram52bc** [comment]
Group leaders (managers) should be identified dynamically with respect to a specific group, rather than a global "group leader" role. Because a manager of one group should not be authorized to modify another group.
