### ISSUE TITLE
Groups - Add DB functionality for multiple managers for one group 

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#442]
Currently, groups and managers have a one to one relation.  Create a new table in the database to allow for a many to many relationship between managers and groups.

- [x] Create a new intermediate table (between managers and groups) in the database to allow for multiple managers to be added to one group.
- [x] Work with @nurkkala (or whoever is currently in charge) to update the ERD accounting for this table.
- [ ] Put some basic data in the table.
- [ ] Design UI layout to display the list of managers (instead of just one manager) for a group, and their management types.

**Comment by PROgram52bc** [comment]
Merged into #494
