### ISSUE TITLE
Groups - Add multiple manager functionality to edit/duplicate/new group

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#445]
Story to complete first: #442 --> sets the DB up

Currently (after that story is completed), in groups, mangers to groups is a many to many relationship and now we have to implement that in the UI.

- [ ] Allow for multiple managers to be assigned to one group.  This should look and work similarly to roles in the people module (go and check this out before completing this story):
![image](https://user-images.githubusercontent.com/29484426/72627434-7f8b7400-391a-11ea-8938-e0d3f4fce40b.png)
- [ ] Create a dropdown from managers that allows users to select one manager (at a time) and after they are clicked, they will appear in the manager box.
- [ ] Once a manager is selected from the dropdown, and they are displayed on the box they should then be removed from the drop-down so that they cannot be added twice.  The drop-down should be dynamic.
- [ ] If the box is clicked on, open the drop-down.
- [ ] There should be small `x`'s next to each manager that are clickable and remove the manager from the group.

**Comment by PROgram52bc** [comment]
#557
