### ISSUE TITLE
Groups - When selecting a manager show all people

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#446]
In groups when selecting a manager, it currently only shows managers.  We want to change this to view all people in the database.  You will most likely have to update the entity search to search through all people and not managers in the manager's table.

- [ ] Change the search field to load people instead of managers.
- [ ] Keep the search field functionality because there will be many names.
- [ ] Manually test this by creating a new person and checking to see that they are in the search field of group managers.

**Comment by PROgram52bc** [comment]
Currently can add any existing person as a manager. #557
