### ISSUE TITLE
Groups - Highlight/Emphasize the manager(s) in the group

### ISSUE THREAD

**Issue by ChrisMaxel** [corpus-christi/corpus-christi#454]
Story to complete first: #439, #445, #442 

When viewing the members of the group, it may be confusing who the manager is.  Emphasize or highlight the manager(s) of the group so that others know who to contact if needed.

- [ ] Attempt to highlight/ make stand out the entire box of the manager in the group by making the border around the manager thicker than the others (or any other way you see fit).  Something like what is shown below (but cleaner).
- [ ] Confirm that this works with multiple managers, highlighting/emphasizing all of them.
![image](https://user-images.githubusercontent.com/29484426/72640192-562c1180-3935-11ea-821f-ad41e2d334de.png)

**Comment by PROgram52bc** [comment]
Currently managers and members are distinguished by using two tables under two tabs, which should serve to eliminate ambiguity in displaying them. #557
