### ISSUE TITLE
Create Meetings toonup UI stuff

### ISSUE THREAD

**Issue by jordaniwoodtaylor** [corpus-christi/corpus-christi#477]
- [x] Add validation so that when a meeting is created, all fields are required and enforced
- [x] Add validation so that you cannot create a meeting that already exists
- [x] After creating a meeting, the fields in the dialog should be cleared. (To see the problem, create a meeting, hit save, then create a meeting again. The fields will already be populated with what you put in the first time)

**Comment by quiteqiang** [comment]
The second question shouldn't be worried. Because the meetings require start time and end time which is almost impossible to create 2 same meetings.
