### ISSUE TITLE
HomeGroup -> Generic Church Group Transition: Refactor Groups API

### ISSUE THREAD

**Issue by mattddean** [corpus-christi/corpus-christi#495]
There are significant changes to be made to the API as a result of this transition. In particular, "Manager" no longer exists and will have to be replaced with "Management." However, it's not as simple as doing a direct replacement, since Management is a many-to-many table, and Manager was a one-to-many table.

Additionally, Member has changed to Membership, and Management Type and Group Type tables have been added.

**Comment by PROgram52bc** [comment]
#494
