### ISSUE TITLE
HomeGroup - Asthetics and user experience

### ISSUE THREAD

**Issue by PROgram52bc** [corpus-christi/corpus-christi#513]
Some thoughts on improving the asthetics and user experience of the home group module

**Comment by quiteqiang** [comment]
- User Experience:
  - [ ] Add attendence to the Meeting page 
  - [ ] Change Group name -> Title
  - [ ] Change `Home Churches` to `Groups` in the side bar
  - [ ] Display error when creating a new person with the same username.

**Comment by PROgram52bc** [comment]
merged into #542
