### ISSUE TITLE
Introduce a standard logging mechanism

### ISSUE THREAD

**Issue by nurkkala** [corpus-christi/corpus-christi#527]
There are many places in the codebase where we generate an error message that will have very little use to the end user but should be something that we track. For example, if a request is made for a model with a bogus ID. This could be because we're being hacked, or because there's an error somewhere in the code.

We need to identify a standard logging mechanism on the server side and use it to log these kinds of detailed, developer-focused messages and integrate it throughout the code base.

**Comment by PROgram52bc** [comment]
fixed in #536
