### ISSUE TITLE
Vuex persistedstate omits object methods

### ISSUE THREAD

**Issue by PROgram52bc** [corpus-christi/corpus-christi#529]
Vuex persistedstate seems to miss synchronizing the `fullName` method after a reload, the result is an error like the following in the browser console when the page is reloaded:

> TypeError: _vm.currentAccount.fullName is not a function

And as a result, the log out button does not appear as well.
This behavior does not show up after the initial login.

**Comment by nurkkala** [comment]
Interesting. The `fullName` method is defined on the `Account` class. I'd guess that the persisted state module is just reloading it as an ordinary JavaScript `Object`.

**Comment by PROgram52bc** [comment]
Yeah. That's my guess, too. It also seems to have caused the behavior described in #526 .
