### ISSUE TITLE
persistent record of membership history

### ISSUE THREAD

**Issue by PROgram52bc** [corpus-christi/corpus-christi#596]
In order to maintain a complete history of which person has been in which group, the following tasks are identified

### API/DB
- [ ] add an `id` field to the `Member` table to allow multiple inactive record with the same identity to coexist
- [ ] implement check in multiple endpoints to make sure no duplicate active record exists
- [ ] add a nullable `left` entry in `Member` table to indicate when a member is deactivated
- [ ] when a `Member` entry is deactivated, set the `left` date to the current date
- [ ] when a `Member` entry is activated, set the `left` date to null
- [ ] when a `Member` entry is created, check among the activated entries (instead of all entries), whether the entry already exists, return a 409 error if already exists
- [ ] modify the `get_all_members` endpoint to return only one copy of each inactive member (preferrably the one with the most recent left date)

#### split group/move members
- [ ] instead of only modifying the member entries, deactivate the first entry, and then create a new one in the destination group. (It still depends on how we want the record to be kept upon a split. Do we want to pretend as if both groups are new groups, or do we want to make it look like some people left the first group and went to the other group? @nurkkala )
- [ ] when moving a person to another group, instead of changing the record, deactivate the current entry, and create another new entry in the destination group (in order to keep the record).
#### group page
- [ ] ~~refactor existing "inactive view" to show only one instance of the inactive record (many inactive records can coexist)~~
- [ ] ~~upon "reactivate" a person, find the inactive record with the most recent "left" date and reactivate that record.~~
- [ ] add option to "permanently delete" an inactive member/manager (in the "inactive view").
#### group history page
- [ ] add a list to show all member history of a certain group
- [ ] provide functionality to delete certain history entry

**Comment by PROgram52bc** [comment]
### Alternative plan for API/DB
- [x] leave the `Member` table as is.
- [x] have another `member_history` table, with the following keys:
   - id (PK)
   - member_id (FK1)
   - group_id (FK2)
   - joined
   - left
- [x] when a `Member` entry is deactivated, the record will be automatically duplicated to `member_history` table, with the current date as `left` date.
- [x] when a `Member` is moved to another group, a record with the previous group would be created in `member_history` table, wit hthe current date as `left` date.
- [x] when a group is splitted into two, duplicate the members who have moved to the new group to `member_history` table.
- [x] add a `get_all_members_history` endpoint to return all member histories.
- [x] add a delete endpoint for `member_history` to delete the history entry.

> The benefit of adopting this structure is that most of the existing code does not need to be changed (e.g. querying of members by their group_id and person_id in the api). And a separate table seems to portray the concept of "history" clearer, rather than mixing existing members with member histories.

**Comment by quiteqiang** [comment]
UI part of the membership history:
- [x] Timeline is required
- [x] Time Line translation
- [x] Permission enforcement for different users
- [x] Other timeline related features are upcoming

**Comment by PROgram52bc** [comment]
## Modify the database structure
The current database structure would not allow asymmetric history to be recorded (member who joined but has not left), also it limits the note taking ability (can't have two separate note each history record that forms a pair).
Below are proposed changes to be made to the database and API to overcome these shortcomings:
### DB
- [x] combine the `joined` and `left` columns in the table to a single `date` column
- [x] add an additional boolean column `is_join`, indicating whether the member is joining (as opposed to leaving) the group
- [x] remove the `joined` column from the `Member` table
### API
- [x] when a member is created, duplicate the record to `member_history` table with the current date
- [x] when a member is activated, duplicate the record to `member_history` table with the current date
- [x] when a member is moved to another group, create a record with the new group in `member_history` table with the current date
- [x] change the semantics of `create_member_history` (can still take a `member` instance as parameter, and take another `is_join` parameter, which defaults to the member's active state)
- [x] change the semantics of factory functions, existing api endpoints (where `create_member_history` is called), tests, etc.
- [x] add corresponding tests

**Comment by quiteqiang** [comment]
Add a text editor into the Page:
- [x]  Implement tiptap with ProseMirror
