### ISSUE TITLE
A tagging system

### ISSUE THREAD

**Issue by PROgram52bc** [corpus-christi/corpus-christi#616]
It would be beneficial to be able to tag different entities with user-defined tags. This is similar to github's "label" system for issues. One use case is in member history, admins might want to tag some of the membership movement as "expected," (e.g. as a result of splitting existing group) which does not necessarily indicate there is a problem in the group. Further functionalities might include filter entities based on their tags, CRUD pattern on tags, etc.
Currently, since there is already a "note" feature for member history, this proposed feature is probably not on the top of the priority list.

**Comment by quiteqiang** [comment]
We replaced this with the "Note-taking feature"
