### ISSUE TITLE
Untranslated tags are hard to find

### ISSUE THREAD

**Issue by nurkkala** [corpus-christi/corpus-christi#711]
With the "Untranslated" filter applied in the toolbox, I expected to see all the untranslated tags. However, I had to hunt around through the top-level tags, eventually checking almost all (dumb luck) of them before having any of the untranslated tags' cards appear.

Possible approaches to make this friendlier:
1. Show cards for all untranslated tags immediately upon checking the filter. To be consistent, the top-level tags for all the untranslated tags should also be checked. This seems simplest.
2. Upon selecting the filter, highlight those top-level tags (in the sidebar) that have untranslated tags and allow the user to select the top-level tags of interest. This would maybe be more performant because we're not showing all the tags?
3. Upon selecting the filter, hide those top-level tags that don't have any untranslated tags. Similar to the previous suggestion, but you wouldn't have to hunt down the list of top-level tags to find the highlighted ones. No need to highlight -- only the top-level tags of interest would be shown.

**Comment by josephvanderharst** [comment]
In [this commit](https://github.com/corpus-christi/corpus-christi/commit/e0e096efea7f8cf3bb6f7ca02a9146d1eb38dbca), the top-level tag chooser has been kitted with extra numbers and a tooltip. The numbers and tooltip reflect the number of untranslated and unverified translations per category, and the tooltip explains this.
