### ISSUE TITLE
Events/CRUD/qa

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#81]
### Functionality Checklist
- [x] 1.  Back-end test for create a new Event. 
   - [x] 2.  End-to-end test for create a new Event.
        - [x] Test for Allowing the event location to be chosen in the following ways:
           - [x] An existing Location using a live search.
           - [x] A past Event location.
- [x] 3. Back-end test for Update an existing Event; provide functionality similar to creating an Event.
   - [x] 4. End-to-end test for Update an existing Event; provide functionality similar to creating an Event.
- [x] 5. Back-end test for Deactivate ("cancel") or reactivate an event.
   - [x] 6. End-to-end test for Deactivate ("cancel") or reactivate an event.
- [x] 7. Back-end test for Duplicate an Event (e.g., Sunday service).
   - [x] 8. End-to-end test for Duplicate an Event (e.g., Sunday service).
      - [x] Take the user to a view where the details of the copy can be updated.

**Comment by Noahffiliation** [comment]
Waiting on creating new locations
