### ISSUE TITLE
assets-CRUD-qa

### ISSUE THREAD

**Issue by jasonlargo** [corpus-christi/corpus-christi#98]
### Functionality Checklist
- [x] 1.  Back-end testing for adding a new Asset. Allow the location to be set using the same criteria as for creating an Event.
- [x] 3. Back-end testing for updating the details for an Asset.
   - [x] 4. End-to-end testing for updating the details for an Asset.
- [x] 5. Back-end testing to deactivate or reactivate an Asset (an inactive Asset is no longer available for future Event's)
   - [x] 6. End-to-end testing to deactivate or reactivate an Asset (an inactive Asset is no longer available for future Event's)

**Comment by Noahffiliation** [comment]
Waiting on the functionality to create a new location
